### ISSUE TITLE
Set custom `User-Agent` header for requests

### ISSUE THREAD

**Issue by brettlangdon** [wp-graphql/wp-graphql-dad-jokes#1]
/me is the creator of https://icanhazdadjoke.com/

Would you mind setting a custom `User-Agent` header for all requests?

https://icanhazdadjoke.com/api#custom-user-agent

Also, WHOOO! Awesome work!

**Comment by jasonbahl** [comment]
@brettlangdon thanks for checking this out!

how does this look? https://github.com/wp-graphql/wp-graphql-dad-jokes/pull/2

**Comment by brettlangdon** [comment]
This was resolved by #2
